// Generated by CoffeeScript 1.8.0
(function() {
  var QueueHandler;

  QueueHandler = (function() {
    function QueueHandler() {}

    QueueHandler.queue = [];

    QueueHandler.requestInProgress = false;

    QueueHandler.retryDelay = 5;

    return QueueHandler;

  })();

}).call(this);
