// Generated by CoffeeScript 1.8.0
(function() {
  document.addEventListener('DOMContentLoaded', function(event) {
    var InvoiceItemModel, escaped_name, hacker, invoiceItemModel;
    event.stopPropagation();
    InvoiceItemModel = Backbone.Model.extend({
      defaults: {
        some: 'some',
        date: function() {
          return new Date().toISOString();
        }
      },
      initialize: function() {
        this.set("prop", "AFTER MODEL COMPLATE SET PROPERTY");
        return this.unset("prop");
      },
      idAttribute: "_id"
    });
    invoiceItemModel = new InvoiceItemModel({
      date: '2013-04-24',
      description: 'alert("Wooden Toy House")',
      price: 22,
      quantity: 3
    });
    console.log(invoiceItemModel.escape('description'));
    hacker = new Backbone.Model({
      name: "<script>alert('xss')</script>"
    });
    escaped_name = hacker.escape('name');
    return console.log(invoiceItemModel);
  });

}).call(this);
