// Generated by CoffeeScript 1.8.0
(function() {
  (function(w) {
    return w.N = {
      ready: function(func) {
        return w.document.addEventListener('DOMContentLoaded', function() {
          return func.call(this);
        });
      }
    };
  })(window);

}).call(this);
