// Generated by CoffeeScript 1.8.0
(function() {
  (function($, n) {
    return n.ready(function() {
      var InvoiceItemModel, PreviewInvoiceItemView, invoiceItemModel, previewInvoiceItemView;
      InvoiceItemModel = Backbone.Model.extend({
        defaults: {
          price: 0,
          quantity: 0
        },
        calculateAmount: function() {
          return this.get('price') * this.get('quantity');
        }
      });
      invoiceItemModel = new InvoiceItemModel({
        price: 2,
        quantity: 3
      });
      PreviewInvoiceItemView = Backbone.View.extend({
        template: _.template('Price: <%= price %>.Quantity: <%= quantity %>.Amounth: <%= amount %>.'),
        render: function() {
          var html;
          html = this.template({
            price: this.model.get('price'),
            quantity: this.model.get('quantity'),
            amount: this.model.calculateAmount()
          });
          return $(this.el).html(html);
        }
      });
      previewInvoiceItemView = new PreviewInvoiceItemView({
        model: invoiceItemModel,
        el: 'body'
      });
      return previewInvoiceItemView.render();
    });
  })(jQuery, N);

}).call(this);
